ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS teaching_subject VARCHAR(80) DEFAULT 'English';

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_unique
  ON users(LOWER(email)) WHERE email IS NOT NULL AND email <> '';
